name: Beer Backend IAC
on:
  push:
    branches:
      - dev
      - integration
      - main

  workflow_dispatch:

env:
  DEPLOYMENT_TYPE: image

jobs:
  set-up-workflow:
    runs-on: ubuntu-latest
      
    #needs: FindAWSAccount!!
    steps:
      - name: Setting environment variable to be used
        run: |
          BRANCH_NAME=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          
          echo "$BRANCH_NAME is the branch and ${{env.DEPLOYMENT_TYPE}} is the deployment type."
          
  aws-cdk-deployment:
    needs: set-up-workflow
    if: (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/integration')
    uses: pallcorporation/digital-iot-devops-store/.github/workflows/beer_aws_cdk_deployment.yml@main
    with:
      branch_name: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
      destroy_stack: false
    secrets:
      envPAT: ${{ secrets.BEER_PROJECT_PROPERTIES }}
  
   docker-image-build:
    needs: set-up-workflow
    if: (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/integration')
    uses: pallcorporation/digital-iot-devops-store/.github/workflows/beer_docker_image_builder.yml@main
    with:
      branch_name: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
      lambd_function_name: beer-membranes
    secrets:
      envPAT: ${{ secrets.BEER_PROJECT_PROPERTIES }}
  
  aws-cdk-deployment-modules:
    needs: docker-image-build
    if: (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/integration')
    uses: pallcorporation/digital-iot-devops-store/.github/workflows/beer_aws_cdk_modules.yml@main
    with:
      branch_name: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
      destroy_stack: false
      config_files_directory: cdk_config
    secrets:
      envPAT: ${{ secrets.BEER_PROJECT_PROPERTIES }}
      #testt
  
  build-main-branch:
    needs: set-up-workflow
    if: (github.ref == 'refs/heads/main' && ${{ github.event.repository.name != "digital-iot-devops-store" }} )
    uses: pallcorporation/digital-iot-devops-store/.github/workflows/beer_main_build.yml@main
    with:
      branch_name: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
      deployment_type: $DEPLOYMENT_TYPE
    secrets:
      envPAT: ${{ secrets.BEER_PROJECT_PROPERTIES }}
