name: Beer Frontend IAC


on:
  push:
    branches:
      - dev
      - integration
  workflow_dispatch:

jobs:
  cicd-deployment:
    uses: pallcorporation/digital-iot-devops-store/.github/workflows/cicd_deployment.yml@main
    with:
      branch_name: ${GITHUB_REF#refs/heads/}
      deploy_to_s3: false