name: Beer Backend IAC
on:
  push:
    branches:
      - dev
      - integration
      - main

  workflow_dispatch:

env:
  DEPLOYMENT_TYPE: image

jobs:
  set-up-workflow:
    runs-on: ubuntu-latest
      
    #needs: FindAWSAccount
    steps:
      - name: Setting environment variable to be used
        run: |
          BRANCH_NAME=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          
          echo "$BRANCH_NAME is the branch and ${{env.DEPLOYMENT_TYPE}} is the deployment type."
  
  docker-image-build:
    needs: set-up-workflow
    if: (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/integration')
    uses: pallcorporation/digital-iot-devops-store/.github/workflows/beer_docker_image_builder.yml@main
    with:
      branch_name: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
      lambd_function_name: lambda-function-name
    secrets:
      envPAT: ${{ secrets.SUPER_SECRET_PASSWORD }}
  
  aws-cdk-deployment-modules:
    needs: docker-image-build
    if: (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/integration')
    uses: pallcorporation/digital-iot-devops-store/.github/workflows/beer_aws_cdk_modules.yml@main
    with:
      branch_name: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
      destroy_stack: false
      config_files_directory: cdk_config
    secrets:
      envPAT: ${{ secrets.SUPER_SECRET_PASSWORD }}
      #testt
  postman-collections-automated-test:
    needs: aws-cdk-deployment-modules 
    if: (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/integration')
    uses: pallcorporation/digital-iot-devops-store/.github/workflows/newman_postman_test.yml@main
    with:
      branch_name: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
      destroy_stack: false
      config_files_directory: cdk_config
    secrets:
      envPAT: ${{ secrets.SUPER_SECRET_PASSWORD }}
      POSTMAN_USERNAME_SECRET: ${{ secrets.SUPER_SECRET_USERNAME }}
      POSTMAN_PASSWORD_SECRET: ${{ secrets.SUPER_SECRET_USER_PASSWORD }}
      COGNITO_DEV_USERPOOL_SECRET_PHRASE: ${{secrets.SUPER_SECRET_CONGITO_PHRASE}}
      COGNITO_INTEGRATION_USERPOOL_SECRET_PHRASE: ${{secrets.SUPER_SECRET_CONGITO_PHRASE_OTHER}}
  
  build-main-branch:
    needs: set-up-workflow
    if: (github.ref == 'refs/heads/main')
    uses: pallcorporation/digital-iot-devops-store/.github/workflows/beer_main_build.yml@main
    with:
      branch_name: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
      deployment_type: $DEPLOYMENT_TYPE
    secrets:
      envPAT: ${{ secrets.SUPER_SECRET_PASSWORD }}
      teams_uri: ${{secrets.TEAMS_WEBHOOK}}