name: Docker Image Builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - dev
      - integration
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

      lambd_function_name:
        required: true
        type: string
      repo_name:
        type: string

      repo_version:
        type: string
    secrets:
      envPAT:
        required: true
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  #BUCKET_NAME : "github-oidc-test-mitch"
  AWS_REGION : "us-east-1"
  PROJECT_FILES_GIT : "beer-project-properties.git"
  ORGANIZATION: "pallcorporation"
  PROJECT_FILES_NAME: "project.properties"
  PROJECT_FILES_DIRECTORY: "project_file"
  IMAGE_REGISTRY: "ghcr.io"
  IMAGE_REGISTRY_USERNAME: ${{github.actor}}
  IMAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v1
      packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  build-docker-image:
    if: ${{inputs.branch_name}} != 'main' && github.repository != 'pallcorporation/digital-iot-devops-store'
    runs-on: ubuntu-latest
      
    #needs: FindAWSAccount
    steps:
        # Get current time stamp to use as reference elsewhere
        - name: Get current date
          id: date
          run: echo "date=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
              
        - name: Check if input is null for repo name
          if: ${{inputs.repo_name}}
          id: repo_name_passed
          run: |
            if [ ${{inputs.repo_name}} != "" ]; then
              echo "reponamepassed=true">>$GITHUB_ENV
            else
              echo "reponamepassed=false">>$GITHUB_ENV
            fi

        - name: Make project files directory
          run: mkdir ${{env.PROJECT_FILES_DIRECTORY}}
        
        - name: Project files clone
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.envPAT }}
            repository: pallcorporation/beer-project-properties
            ref: main
            path: ${{env.PROJECT_FILES_DIRECTORY}}
        
        # Get branch name to use for look up
        - name: Branch
          run: |
            echo "BRANCH_NAME=Beta" >> $GITHUB_ENV
        
        - name: Branch if Main
          if: contains( github.ref, 'main' )
          run: |
            echo "BRANCH_NAME=production" >> $GITHUB_ENV
        
        - name: Branch if BETA
          if: contains( github.ref, 'beta' )
          run: |
            echo "BRANCH_NAME=beta" >> $GITHUB_ENV
        
        - name: Lambda function environment suffix
          id: get_aws_branch_name
          run: |
            if [[ ${{inputs.branch_name}} == 'main' ]]
            then
              echo "AWS_ENV_NAME=production" >> $GITHUB_ENV
            elif [[ ${{inputs.branch_name}} == 'beta' ]]
            then
              echo "AWS_ENV_NAME=beta" >> $GITHUB_ENV
            fi
        
        # Read of project files and set to variables
        - name: Get project constants from project.properties repo - Branch name, deployment role, skip cdk, destroy stack
          id: project_constants
          run: |
            account_id="`grep aws_${BRANCH_NAME}_account ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
            echo "AWS_ENVIRONMENT=${account_id}" >> $GITHUB_ENV
            
            oidc_role_name="`grep aws_${BRANCH_NAME}_oidc_role_name ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
            echo "oidc_role=${oidc_role_name}" >> $GITHUB_ENV 

          working-directory: ${{env.PROJECT_FILES_DIRECTORY}}
        
        - name: Get project constants from project.properties repo - Branch name, deployment role, skip cdk, destroy stack
          if: ${{ env.reponamepassed }}
          id: project_constants_tools
          run: |
            account_id="`grep aws_tools_account ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
            echo "AWS_ENVIRONMENT=${account_id}" >> $GITHUB_ENV
            
            oidc_role_name="`grep aws_tools_oidc_role_name ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
            echo "oidc_role=${oidc_role_name}" >> $GITHUB_ENV

          working-directory: ${{env.PROJECT_FILES_DIRECTORY}}

        # Role that will be used for OIDC. This is the role this session will assume when connecting to AWS         
        - name: Arn to use
          id: aws_assume_role
          run: |
            echo "OCID_ROLE_ARN=arn:aws:iam::${{ env.AWS_ENVIRONMENT }}:role/${{ env.oidc_role}}" >> $GITHUB_ENV

        - name: Arn to use (If Application deployment)
          id: aws_assume_role_tools
          if: ${{ env.reponamepassed }}
          run: |
            echo "OCID_ROLE_ARN=arn:aws:iam::${{ env.AWS_ENVIRONMENT }}:role/${{ env.oidc_role}}" >> $GITHUB_ENV
        
        - name: Configure AWS credentials
          id: aws_oidc_credentials
          uses: aws-actions/configure-aws-credentials@master
          with:
            role-to-assume: ${{env.OCID_ROLE_ARN}}
            role-session-name: ${{ github.event.repository.name }}-${{ env.date }}
            aws-region: ${{ env.AWS_REGION }}
        
        - name: Version number (If application deployment)
          run: |
            echo "TAG_VERSION=${{ inputs.repo_version }}" >> $GITHUB_ENV
 
        # Node installation (if required)
        - name: Setup node.js environment
          uses: actions/setup-node@v3.6.0
        
        - name: Image Repository name (If application deployment)
          run: |
            echo "IMAGE_REPO_NAME=${{inputs.repo_name}}" >> $GITHUB_ENV
        
        - name: ECR Registry
          run: |
            echo DOCKER_TAG_VERSION="${{ env.AWS_ENVIRONMENT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${IMAGE_REPO_NAME}:${TAG_VERSION}" >> $GITHUB_ENV

        - name: ECR Login
          id: ecr_login
          run: |
            (aws ecr describe-repositories --repository-names ${IMAGE_REPO_NAME} && echo "repo_created=false">>$GITHUB_ENV ) || ( aws ecr create-repository --repository-name ${IMAGE_REPO_NAME} && echo "repo_created=true">>$GITHUB_ENV )
            aws ecr get-login-password --region ${{ env.AWS_REGION }}| docker login --username AWS --password-stdin ${AWS_ENVIRONMENT}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

        - name: Lambda function name
          run: |
            echo LAMBDA_FUNCTION_NAME="${{inputs.lambd_function_name}}-${{ env.AWS_ENV_NAME }}" >> $GITHUB_ENV

        - name: Update function with new image built
          run: |
            aws lambda update-function-code --region ${{ env.AWS_REGION }} --function-name $LAMBDA_FUNCTION_NAME --image-uri $DOCKER_TAG_VERSION
