name: Release Tagging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

      deployment_type:
        required: true
        type: string

    secrets:
      envPAT:
        required: true
      teams_uri:
        required: false

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  #BUCKET_NAME : "github-oidc-test-mitch"
  AWS_REGION : "us-east-1"
  PROJECT_FILES_GIT : "beer-project-properties.git"
  ORGANIZATION: "pallcorporation"
  PROJECT_FILES_NAME: "project.properties"
  PROJECT_FILES_DIRECTORY: "project_file"
  IMAGE_REGISTRY: "ghcr.io"
  IMAGE_REGISTRY_USERNAME: ${{github.actor}}
  IMAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}


permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v1
      packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  tag-and-build:
    if: (github.repository != 'pallcorporation/digital-iot-devops-store' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest          
    steps:

        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"

        #- name: Login to docker
        #  if: |
        #    ${{ steps.skip_dk_build.outputs.bypass_dk_build !='true' && inputs.deployment_type == 'image' }}
        #  uses: docker/login-action@v1
        #  with:
        #    registry: ${{env.IMAGE_REGISTRY}}
        #    username: ${{env.IMAGE_REGISTRY_USERNAME}}
        #    password: ${{env.IMAGE_REGISTRY_TOKEN}}
        
        # Clone repositories prior to work
        - name: Git clone the repository
          uses: actions/checkout@v2

        