name: Create Release

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_call:
    inputs:
      version_number:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
      teams_uri:
        required: false

env:
  #BUCKET_NAME : "github-oidc-test-mitch"
  AWS_REGION : "us-east-1"
  PROJECT_FILES_GIT : "beer-project-properties.git"
  ORGANIZATION: "pallcorporation"
  PROJECT_FILES_NAME: "project.properties"
  PROJECT_FILES_DIRECTORY: "beer-project-properties"
  IMAGE_REGISTRY: "ghcr.io"
  IMAGE_REGISTRY_USERNAME: ${{github.actor}}
  IMAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NX_ARTIFACT_STORE: beer-ul-nx-workspace

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout@v1
  packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Project files clone
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.envPAT }}
          repository: pallcorporation/beer-project-properties
          ref: main
          path: ${{env.PROJECT_FILES_DIRECTORY}}
        
      - name: Release assets clone
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.envPAT }}
          repository: pallcorporation/beer-release-assets
          ref: main
          path: beer-release-assets
      
      # Grant permissions to all files in directory
      - name: Grant permissions to all files
        run: chmod -R 755 ./  
        
      # Read of project files and set to variables
      - name: Get project constants from project.properties
        id: project_constants
        run: |
          account_id="`grep aws_tools_account ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"

          echo "tools_account_id=${account_id}" >> $GITHUB_ENV

          oidc_role="`grep aws_tools_oidc_role_name ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
          echo "oidc_role_name=${oidc_role}" >> $GITHUB_ENV
          
        working-directory: ${{env.PROJECT_FILES_DIRECTORY}}

      # Role that will be used for OIDC. This is the role this session will assume when connecting to AWS         
      - name: Tools Arn to use
        id: aws_assume_role
        run: |
          echo "role_arn1=arn:aws:iam::${{env.tools_account_id}}:role/${{ env.oidc_role_name}}">> $GITHUB_ENV

      - name: Jira Username & Secret name
        run: |
          echo "JIRA_API_USER=mitchell_boulay@pall.com" >> $GITHUB_ENV
          echo "AWS_SECRET_NAME_JIRA=Jira-API-Token-MitchellBoulay" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.role_arn1 }}
          role-session-name: ${{ github.event.repository.name }}-${{ env.date }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Install release assets requirements
        run: |
          pip3 install -r beer-release-assets/requirements.txt
      
      - name: Get release info from jira
        run: |
          python3 beer-release-assets/current_brew_jira_release.py > release.txt
          echo "RELEASE_NAME=$(cat release.txt)" >> $GITHUB_ENV

          cat release.properties

          release_name="`grep RELEASE_NAME release.properties|cut -d'=' -f2`"
          echo "RELEASE_NAME=${release_name}" >> $GITHUB_ENV

          release_start_date="`grep RELEASE_START_DATE release.properties|cut -d'=' -f2`"
          echo "RELEASE_START_DATE=${release_start_date}" >> $GITHUB_ENV

          release_end_date="`grep RELEASE_END_DATE release.properties|cut -d'=' -f2`"
          echo "RELEASE_END_DATE=${release_end_date}" >> $GITHUB_ENV

          release_description="`grep RELEASE_DESCRIPTION release.properties|cut -d'=' -f2`"
          echo "RELEASE_DESCRIPTION=${release_description}" >> $GITHUB_ENV

          echo "REPOSITORY_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "VERSION_TAG=v${{ inputs.version_number }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.envPAT }}" >> $GITHUB_ENV

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@master
        with:
          generate_release_notes: True
          token: ${{ secrets.envPAT }}
          name: ${{env.RELEASE_NAME}} v${{ inputs.version_number }}
          tag_name: v${{ inputs.version_number }}
      
      - name: Release notes clone
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.envPAT }}
          repository: pallcorporation/beer-ul-release-notes
          ref: main
          path: beer-ul-release-notes
      
      - name: Publish release notes to Confluence
        run: |
          python3 beer-ul-release-notes/github.py
    
      - name: File name of chagelog
        run:
          echo "CHANGELOG_FILE=${{ github.event.repository.name }}_v${{ inputs.version_number }}.md" >> $GITHUB_ENV
      - name: Read the change log
        run: echo ${{ steps.Changelog.outputs.changelog }}
        
      - name: Copy release file to s3
        run: |
          mkdir release_notes
          echo ${{ steps.Changelog.outputs.changelog }} > release_notes/${{env.CHANGELOG_FILE}}
      
      # Upload artifacts to Git for easy access
      - uses: actions/upload-artifact@v2
        with:
          name: release_notes
          path: release_notes/