name: Beer Cloudwatch Monitoring API automated tests
on:
  
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

    secrets:
      envPAT:
        required: true
      teams_uri:
        required: false
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION : "us-east-1"
  PROJECT_FILES_GIT : "beer-project-properties.git"
  PROJECT_FILES_NAME: "project.properties"
  PROJECT_FILES_DIRECTORY: "beer-project-properties"
  LOGS_MONITORING_REPO: "beer-be-logs-monitoring"
  
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v1 !
      packages: write

jobs:
  Project-Admins:
    runs-on: ubuntu-latest
    steps:
      # Get current time stamp to use as reference elsewhere
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
      
      - name: Git clone the repository
        uses: actions/checkout@v2

      - name: Branch name
        id: get_branch_name
        run: |
          echo "BRANCH_NAME=${{inputs.branch_name}}" >> $GITHUB_ENV
      
      # Get branch name to use for look up
      - name: Branch if Dev
        if: contains( github.ref, 'dev' )
        run: |
          echo "BRANCH_NAME=dev" >> $GITHUB_ENV
      
      - name: Branch if Integration
        if: contains( github.ref, 'integration' )
        run: |
          echo "BRANCH_NAME=integration" >> $GITHUB_ENV

      - name: Branch if Production
        if: contains( github.ref, 'production' )
        run: |
          echo "BRANCH_NAME=production" >> $GITHUB_ENV
      
      - name: Branch if BETA
        if: contains( github.ref, 'beta' )
        run: |
          echo "BRANCH_NAME=beta" >> $GITHUB_ENV
      
      - name: Branch if Tools
        if: contains( github.ref, 'tools' )
        run: |
          echo "BRANCH_NAME=tools" >> $GITHUB_ENV
      
      - name: Project files clone
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.envPAT }}
          repository: pallcorporation/beer-project-properties
          ref: main
          path: ${{env.PROJECT_FILES_DIRECTORY}}
      
      - name: Get project constants from project.properties repo
        id: project_constants
        run: |
          account_id="`grep aws_${BRANCH_NAME}_account ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
          echo "AWS_ENVIRONMENT=${account_id}" >> $GITHUB_ENV
          
          oidc_role_name="`grep aws_${BRANCH_NAME}_oidc_role_name ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
          echo "oidc_role=${oidc_role_name}" >> $GITHUB_ENV
          
        working-directory: ${{env.PROJECT_FILES_DIRECTORY}}
      
      # Role that will be used for OIDC. This is the role this session will assume when connecting to AWS         
      - name: Arn to use
        id: aws_assume_role
        run: |
          echo "AWS_ASSUME_ROLE=arn:aws:iam::${{ env.AWS_ENVIRONMENT }}:role/${{ env.oidc_role}}" >> $GITHUB_ENV
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{env.AWS_ASSUME_ROLE}}
          role-session-name: ${{ github.event.repository.name }}-${{ env.date }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Set teams URI to environment Variable
        run: |
          echo "TEAMS_URI=${{secrets.teams_uri}}" >> $GITHUB_ENV
      - name: Install dependencies
        run: pip3 install -r requirements.txt
        
      - name: Run python script to read Cloudwatch logs
        run: |
          python3 app.py
      
      