name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches:
  #    - dev
  #    - integration
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      
      destroy_stack:
        type: boolean
        default: false

      deployment_type:
        type: string
      config_files_directory:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
      POSTMAN_USERNAME_SECRET:
        required: true
      POSTMAN_PASSWORD_SECRET:
        required: true
      COGNITO_DEV_USERPOOL_SECRET_PHRASE:
        required: true
      COGNITO_INTEGRATION_USERPOOL_SECRET_PHRASE:
        required: true
      teams_uri:
        required: false
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  #BUCKET_NAME : "github-oidc-test-mitch"
  AWS_REGION : "us-east-1"
  PROJECT_FILES_GIT : "beer-project-properties.git"
  ORGANIZATION: "pallcorporation"
  PROJECT_FILES_NAME: "project.properties"
  PROJECT_FILES_DIRECTORY: "project_file"
  IMAGE_REGISTRY: "ghcr.io"
  IMAGE_REGISTRY_USERNAME: ${{github.actor}}
  IMAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CDK_MODULE: "cdk_checkedout"
  API_GATEWAY_STACK_ID: beer-apigateway-0-iot-apigw
  API_GATEWAY_OUPUT_LOOKUP: beerapigateway0iotapigwurloutput
  POSTMAN_COLLECTION_DIRECTORY: "newman_collection"
  REPO_NAME: ${{ github.event.repository.name }}
  ADMIN_USERS_POLICY_SEED: beer-ul-admin-users
  IAM_SERVICE_REPOSITORY: beer-be-iam-service
  COGNITO_USER_POOL_STACK_ID: beer-cognito-0-user-pool
  COGNITO_USER_POOL_ID_OUTPUT: beercognito0userpoolidoutput
  API_GATEWAY_STACKID_OUT: beer-apigateway-0-iot-apigw
  API_GATEWAY_URL_OUT: beerapigateway0iotapigwurloutput

  

permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v1
      packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  AWS-CDK-Deployment:
    if: github.repository != 'pallcorporation/digital-iot-devops-store'
    runs-on: ubuntu-latest
      
    steps:
        # Get current time stamp to use as reference elsewhere
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"
        
        # Get branch name to use for look up
        - name: Branch if Dev
          if: contains( github.ref, 'dev' )
          run: |
            echo "BRANCH_NAME=dev" >> $GITHUB_ENV
        
        - name: Branch if Integration
          if: contains( github.ref, 'integration' )
          run: |
            echo "BRANCH_NAME=integration" >> $GITHUB_ENV

        - name: Branch if users
          if: contains( github.ref, 'users' )
          run: |
            echo "BRANCH_NAME=dev" >> $GITHUB_ENV
        
        - name: Branch if Main
          if: contains( github.ref, 'main' )
          run: |
            echo "BRANCH_NAME=production" >> $GITHUB_ENV
        
        # Clone repositories prior to work
        - name: Git clone the repository
          uses: actions/checkout@v2
        
        - name: Make Newman directory
          run: mkdir ${{env.POSTMAN_COLLECTION_DIRECTORY}}

        - name: Make postman directory (authorizer test)
          if: ${{env.REPO_NAME == 'beer-be-api-authorizer' }}
          run: |
            DIR="postman/"
            if [ -d "$DIR" ]; then
              # Take action if $DIR exists. #
              echo "Installing config files in ${DIR}..."
              echo "::set-output name=postman_collections_found::true"
            else
              mkdir postman
            fi
            
        - name: Postman repo clone
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.envPAT }}
            repository: pallcorporation/beer-ul-postman-env
            ref: main
            path: ${{env.POSTMAN_COLLECTION_DIRECTORY}}

        - name: Admin users repo clone
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.envPAT }}
            repository: pallcorporation/beer-ul-admin-users
            ref: main
            path: ${{env.ADMIN_USERS_POLICY_SEED}}
        
        - name: Clone default repository (authorizer test)
          if: ${{env.REPO_NAME == 'beer-be-api-authorizer' }}
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.envPAT }}
            repository: pallcorporation/beer-be-company-service
            ref: ${{env.BRANCH_NAME}}
            path: beer-be-company-service
        
        - name: Project files clone
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.envPAT }}
            repository: pallcorporation/beer-project-properties
            ref: main
            path: ${{env.PROJECT_FILES_DIRECTORY}}
        # Read of project files and set to variables
        - name: Get project constants from project.properties repo - Branch name, deployment role, skip cdk, destroy stack
          id: project_constants
          run: |
            account_id="`grep aws_${BRANCH_NAME}_account ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
            echo "::set-output name=env_id::${account_id}"
            echo $account_id is the account id
            echo "AWS_ACCOUNT=${account_id}" >> $GITHUB_ENV
            

            oidc_role_name="`grep aws_${BRANCH_NAME}_oidc_role_name ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
            echo "::set-output name=oidc_role::${oidc_role_name}"

            cdk_deploy_role_arn="`grep aws_${BRANCH_NAME}_cdk_deployment_role ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
            echo "::set-output name=cdk_deploy::${cdk_deploy_role_arn}"
            
            aws_bucket="`grep aws_frontend_bucket ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
            echo "::set-output name=aws_bucket_name::${aws_bucket}"
            echo $aws_bucket

            cloud_front_id="`grep aws_${BRANCH_NAME}_cloudfront_id ${{env.PROJECT_FILES_NAME}}|cut -d'=' -f2`"
            echo "::set-output name=aws_cloud_front_id::${cloud_front_id}"
          working-directory: ${{env.PROJECT_FILES_DIRECTORY}}
        
        
        
        # Role that will be used for OIDC. This is the role this session will assume when connecting to AWS         
        - name: Arn to use
          id: aws_assume_role
          run: |
            echo "::set-output name=role_arn1::arn:aws:iam::${{ steps.project_constants.outputs.env_id }}:role/${{ steps.project_constants.outputs.oidc_role}}"
      
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@master
          with:
            role-to-assume: ${{steps.aws_assume_role.outputs.role_arn1}}
            role-session-name: ${{ github.event.repository.name }}-${{ steps.date.outputs.date }}
            aws-region: ${{ env.AWS_REGION }}
        
        - name: API Gateway output
          run: |
            echo "API_GATEWAY_STACKID_OUT=beerapigateway0iotapigwurloutput" >> $GITHUB_ENV
            echo "API_GATEWAY_URL=$(aws cloudformation --region ${{ env.AWS_REGION }} describe-stacks --stack-name ${{env.API_GATEWAY_STACKID_OUT}} --query 'Stacks[0].Outputs[?OutputKey==`${{env.API_GATEWAY_URL_OUT}}`].OutputValue' --output text)" >> $GITHUB_ENV

        
        - name: Make ${{env.IAM_SERVICE_REPOSITORY}}
          run: |
            mkdir ${{env.IAM_SERVICE_REPOSITORY}}
        
        - name: beer-be-iam-service repo clone
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.envPAT }}
            repository: pallcorporation/beer-be-iam-service
            ref: main
            path: ${{env.IAM_SERVICE_REPOSITORY}}
        
        # Grant permissions to all files in directory
        - name: Grant permissions to all files
          run: chmod -R 755 ./

        - name: Copy file to use
          run: |
            cp ${{env.POSTMAN_COLLECTION_DIRECTORY}}/${{env.BRANCH_NAME}}_env_var.json env_var.json

        - name: Set environment variables for python
          run: |
            if [[ ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}} == 'dev' ]]
            then
              echo "COGNITO_USERPOOL_SECRET=${{secrets.COGNITO_DEV_USERPOOL_SECRET_PHRASE}}" >> $GITHUB_ENV
            elif [[ ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}} == 'integration' ]]
            then
              echo "COGNITO_USERPOOL_SECRET=${{secrets.COGNITO_INTEGRATION_USERPOOL_SECRET_PHRASE}}" >> $GITHUB_ENV
            else
              echo "COGNITO_USERPOOL_SECRET=${{secrets.COGNITO_DEV_USERPOOL_SECRET_PHRASE}}" >> $GITHUB_ENV
            fi
        
        - name: Postman required variables
          run: |
            echo "CREATE_POSTMAN_USER=True" >> $GITHUB_ENV
        
        - name: Cognito User Pool query
          id: get_user_pool_id
          run: |
            echo "COGNITO_USERPOOL_ID=$(aws cloudformation --region ${{ env.AWS_REGION }} describe-stacks --stack-name ${{env.COGNITO_USER_POOL_STACK_ID}} --query 'Stacks[0].Outputs[?OutputKey==`${{env.COGNITO_USER_POOL_ID_OUTPUT}}`].OutputValue' --output text)" >> $GITHUB_ENV
        

        - name: Run python script to seed policy to admins
          run: |
            ls
            rm -rf ${{env.ADMIN_USERS_POLICY_SEED}}/super-user-policy.json
            cp ${{env.IAM_SERVICE_REPOSITORY}}/seeding-data/super-user-policy.jsonc ${{env.ADMIN_USERS_POLICY_SEED}}/super-user-policy.json
            pip3 install boto3
            pip3 install pytz
            python3 ${{env.ADMIN_USERS_POLICY_SEED}}/admins.py
        
        - name: Run python script to Confirm or create envrionment admin user
          run: |
            python3 ${{env.ADMIN_USERS_POLICY_SEED}}/create_environment_user.py

        - name: Read output file from seed
          run: |
            cat deploy_data.properties

            COGNITO_USERNAME="`grep COGNITO_USERNAME deploy_data.properties|cut -d'=' -f2`"
            echo "POSTMAN_USERNAME=${COGNITO_USERNAME}" >> $GITHUB_ENV

            COGNITO_PASSWORD="`grep COGNITO_PASSWORD deploy_data.properties|cut -d'=' -f2`"
            echo "POSTMAN_PASSWORD=${COGNITO_PASSWORD}" >> $GITHUB_ENV

        - name: Run python script to replace secrets
          run: |
            python3 ${{env.POSTMAN_COLLECTION_DIRECTORY}}/replace_secrets.py
            ls
            
        - name: Move postman files (authorizer test)
          if: ${{env.REPO_NAME == 'beer-be-api-authorizer' }}
          run: |
            mv beer-be-company-service/postman/* postman
        
        # Node installation (if required)
        - name: Setup node.js environment
          uses: actions/setup-node@v2.1.2
        
        - name: Install newman
          run: |
            npm install -g newman
        
        - name: Check if postman collections exists
          id: postman_collections
          run: |
            DIR="postman/"
            ls
            if [ -d "$DIR" ]; then
              # Take action if $DIR exists. #
              echo "Installing config files in ${DIR}..."
              echo "::set-output name=postman_collections_found::true"
            fi
        
        - name: Collections found
          run: |
            echo ${{steps.postman_collections.outputs.postman_collections_found}}

        - name: run newman
          if: ${{steps.postman_collections.outputs.postman_collections_found == 'true'}}
          run: |
            newman run ./postman/collection.json -e ./final_env_var.json
        
        - name: Python script to disable & delete created postman user
          if: always()
          run: |
            echo "DELETE_POSTMAN_USER=True"
            python3 ${{env.ADMIN_USERS_POLICY_SEED}}/delete_user.py
        
        - name: Microsoft Teams Notification
          if: failure()
          uses: jdcargile/ms-teams-notification@v1.3
          with:
            github-token: ${{ secrets.envPAT }} # this will use the runner's token.
            ms-teams-webhook-uri: ${{ secrets.teams_uri }}
            notification-summary: "${{ github.event.repository.name }} test error on ${{env.BRANCH_NAME}} branch  &#x274C; : Please test results."
            notification-color: FF0000
            timezone: America/New_York